CREATE DATABASE IF NOT EXISTS PISCA;
USE PISCA;

CREATE USER 'javapisca'@'localhost' IDENTIFIED BY '2306121984';
GRANT ALL PRIVILEGES ON PISCA.* TO 'javapisca'@'localhost';
FLUSH PRIVILEGES;

CREATE TABLE MODELO(
    idModelo INT AUTO_INCREMENT UNIQUE,
    Nome VARCHAR(150) NOT NULL,
    idMarca INT NOT NULL
);
ALTER TABLE MODELO ADD CONSTRAINT PK_Modelo PRIMARY KEY(idModelo);

CREATE TABLE MARCA(
    idMarca INT AUTO_INCREMENT UNIQUE,
    Nome VARCHAR(50) NOT NULL UNIQUE
);
ALTER TABLE MARCA ADD CONSTRAINT PK_Marca PRIMARY KEY(idMarca);

CREATE TABLE CLIENTE(
	idCliente INT AUTO_INCREMENT UNIQUE,
    Nome VARCHAR(200) NOT NULL,
    WhatsApp VARCHAR(20) NOT NULL,
    DataCadastro DATE DEFAULT (CURRENT_DATE)
);

ALTER TABLE CLIENTE ADD CONSTRAINT PK_Clientes PRIMARY KEY(idCliente);

CREATE TABLE ORDEMSERVICO(
	idOrdemServico INT AUTO_INCREMENT UNIQUE,
    valorCobrado DECIMAL(10,2) NOT NULL,
    idCarro INT NOT NULL,
    idStatusOS INT NOT NULL,
    DataAbertura DATETIME NOT NULL
);
ALTER TABLE ORDEMSERVICO ADD CONSTRAINT PK_OrdemDeServico PRIMARY KEY(idOrdemServico);

CREATE TABLE ITEMOS(
    idItemOS INT AUTO_INCREMENT UNIQUE,
    idOrdemServico INT NOT NULL,
    idServico INT NOT NULL,
    valorCobrado DECIMAL(8,2) NOT NULL
);

ALTER TABLE ITEMOS ADD CONSTRAINT PK_ItemOS PRIMARY KEY(idItemOS);


CREATE TABLE SERVICO(
	idServico INT AUTO_INCREMENT UNIQUE,
    Nome VARCHAR(100) NOT NULL,
    Valor DECIMAL(8,2) NOT NULL
    
);

ALTER TABLE SERVICO ADD CONSTRAINT PK_Servicos PRIMARY KEY(idServico);

CREATE TABLE CARRO(
	idCarro INT AUTO_INCREMENT UNIQUE,
    idCliente INT NOT NULL,
	idModelo INT NOT NULL,
    Placa CHAR(7) NOT NULL
    
);

ALTER TABLE CARRO ADD CONSTRAINT PK_Carros PRIMARY KEY(idCarro);

CREATE TABLE STATUSOS(
	idStatusOS INT AUTO_INCREMENT UNIQUE,
    descricao VARCHAR(30)
);

ALTER TABLE STATUSOS ADD CONSTRAINT PK_StatusOS
PRIMARY KEY(idStatusOS);

ALTER TABLE ITEMOS
ADD CONSTRAINT FK_ORDEMSERVICO_ITEMOS
FOREIGN KEY (idOrdemServico) REFERENCES ORDEMSERVICO(idOrdemServico);

ALTER TABLE ITEMOS
ADD CONSTRAINT FK_SERVICO_ITEMOS
FOREIGN KEY (idServico) REFERENCES SERVICO(idServico);

ALTER TABLE CARRO
ADD CONSTRAINT UQ_Carro_Placa
UNIQUE(Placa);

ALTER TABLE MODELO
ADD CONSTRAINT UQ_Modelo_Nome
UNIQUE(Nome);

ALTER TABLE MARCA
ADD CONSTRAINT UQ_Marca_Nome
UNIQUE(Nome);

ALTER TABLE CARRO
ADD CONSTRAINT FK_Cliente_Carro
FOREIGN KEY(idCliente) REFERENCES CLIENTE(idCliente)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE ORDEMSERVICO 
ADD CONSTRAINT FK_CARRO_ORDEMSERVICO
FOREIGN KEY (idCarro) REFERENCES CARRO(idCarro)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE ORDEMSERVICO 
ADD CONSTRAINT FK_STATUSOS_ORDEMSERVICO
FOREIGN KEY (idStatusOS) REFERENCES STATUSOS(idStatusOS)
ON DELETE RESTRICT
ON UPDATE RESTRICT;

ALTER TABLE MODELO 
ADD CONSTRAINT FK_MARCA_MODELO
FOREIGN KEY(idMarca) REFERENCES MARCA(idMarca)
ON DELETE RESTRICT
ON UPDATE RESTRICT;


ALTER TABLE CARRO 
ADD CONSTRAINT FK_Modelo_Carro
FOREIGN KEY(idModelo) REFERENCES MODELO(idModelo)
ON DELETE RESTRICT
ON UPDATE RESTRICT;

CREATE INDEX IDX_Carro_Cliente ON CARRO(idCliente);
CREATE INDEX IDX_Os_Carro ON ORDEMSERVICO(idCarro);
CREATE INDEX IDX_OS_ItemOS ON ITEMOS(idOrdemServico);



