CREATE DATABASE IF NOT EXISTS PISCA;
USE PISCA;

CREATE USER 'javapisca'@'localhost' IDENTIFIED BY '2306121984';
GRANT ALL PRIVILEGES ON PISCA.* TO 'javapisca'@'localhost';
FLUSH PRIVILEGES;

CREATE TABLE MODELO(
    idModelo INT AUTO_INCREMENT,
    Nome VARCHAR(150) NOT NULL,
    idMarca INT NOT NULL,
    CONSTRAINT PK_Modelo PRIMARY KEY(idModelo)
);

CREATE TABLE MARCA(
    idMarca INT AUTO_INCREMENT,
    Nome VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT PK_Marca PRIMARY KEY(idMarca)
);

CREATE TABLE CLIENTE(
	idCliente INT AUTO_INCREMENT,
    Nome VARCHAR(200) NOT NULL,
    WhatsApp VARCHAR(20) NOT NULL,
    DataCadastro DATE NOT NULL,
    CONSTRAINT PK_Clientes PRIMARY KEY(idCliente)
);

CREATE TABLE ORDEMSERVICO(
	idOrdemServico INT AUTO_INCREMENT,
    valorCobrado DECIMAL(10,2) NOT NULL,
    idCarro INT NOT NULL,
    idStatusOS INT NOT NULL,
    DataAbertura DATETIME NOT NULL,
    CONSTRAINT PK_OrdemDeServico PRIMARY KEY(idOrdemServico)
);

CREATE TABLE ITEMOS(
    idItemOS INT AUTO_INCREMENT,
    idOrdemServico INT NOT NULL,
    idServico INT NOT NULL,
    CONSTRAINT PK_ItemOS PRIMARY KEY(idItemOS)
);

CREATE TABLE SERVICO(
	idServico INT AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    Valor DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_Servicos PRIMARY KEY(idServico)
);

CREATE TABLE CARRO(
	idCarro INT AUTO_INCREMENT,
    idCliente INT NOT NULL,
	idModelo INT NOT NULL,
    Placa CHAR(7) NOT NULL,
    CONSTRAINT PK_Carros PRIMARY KEY(idCarro)
);

CREATE TABLE ORCAMENTO(
	idOrcamento INT AUTO_INCREMENT,
    idCarro INT NOT NULL,
    descricao VARCHAR(300) NOT NULL,
    DataChegada DATE NOT NULL,
    ValorCobrado DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_Orcamento PRIMARY KEY(idOrcamento)
);

CREATE TABLE STATUSOS(
	idStatusOS INT AUTO_INCREMENT,
    descricao VARCHAR(30),
    CONSTRAINT PK_StatusOS PRIMARY KEY(idStatusOS)
);

ALTER TABLE ITEMOS
ADD CONSTRAINT FK_ORDEMSERVICO_ITEMOS
FOREIGN KEY (idOrdemServico) REFERENCES ORDEMSERVICO(idOrdemServico);

ALTER TABLE ITEMOS
ADD CONSTRAINT FK_SERVICO_ITEMOS
FOREIGN KEY (idServico) REFERENCES SERVICO(idServico);

ALTER TABLE CARRO
ADD CONSTRAINT UQ_Placa_Nome
UNIQUE(Placa);

ALTER TABLE MODELO
ADD CONSTRAINT UQ_Modelo_Nome
UNIQUE(Nome);

ALTER TABLE MARCA
ADD CONSTRAINT UQ_Marca_Nome
UNIQUE(Nome);

ALTER TABLE CARRO
ADD CONSTRAINT FK_Cliente_Carro
FOREIGN KEY(idCliente) REFERENCES CLIENTE(idCliente);

ALTER TABLE ORCAMENTO 
ADD CONSTRAINT FK_Carro_Orcamento
FOREIGN KEY (idCarro) REFERENCES CARRO(idCarro);

ALTER TABLE ORDEMSERVICO 
ADD CONSTRAINT FK_CARRO_ORDEMSERVICO
FOREIGN KEY (idCarro) REFERENCES CARRO(idCarro);

ALTER TABLE ORDEMSERVICO 
ADD CONSTRAINT FK_STATUSOS_ORDEMSERVICO
FOREIGN KEY (idStatusOS) REFERENCES STATUSOS(idStatusOS);

ALTER TABLE MODELO 
ADD CONSTRAINT FK_MARCA_MODELO
FOREIGN KEY(idMarca) REFERENCES MARCA(idMarca);

ALTER TABLE CARRO 
ADD CONSTRAINT FK_Modelo_Carro
FOREIGN KEY(idModelo) REFERENCES MODELO(idModelo);


DELIMITER $

CREATE PROCEDURE sp_historicoCarro(Placa CHAR(7))
BEGIN
    SELECT 
    c.Placa,
    os.idOrdemServico,
    s.Nome AS Servico,
    os.valorCobrado
    FROM ORDEMSERVICO os
    JOIN CARRO c ON os.idCarro = c.idCarro
    JOIN ITEMOS ios ON os.idOrdemServico = ios.idOrdemServico
    JOIN SERVICO s ON ios.idServico = s.idServico
    WHERE c.Placa = Placa;
END
$


DELIMITER ;